dtb-$(CONFIG_ARCH_S32) += s32v234-bbmini.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-evb28899.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-evb.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-evbbcm.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-palladium.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-pciebcm.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-pcie.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-simulator.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234-tmdp.dtb
dtb-$(CONFIG_ARCH_S32) += s32v344-simulator.dtb
dtb-$(CONFIG_ARCH_S32) += s32g275-simulator.dtb
dtb-$(CONFIG_ARCH_S32) += s32r45x-simulator.dtb
dtb-$(CONFIG_ARCH_S32) += s32v234sbc.dtb
dtb-$(CONFIG_ARCH_FSL_LS2085A) += fsl-ls2085a-simu.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
