dtb-$(CONFIG_S32V234_EVB) += s32v234-evb.dtb
dtb-$(CONFIG_S32V234_PALLADIUM) += s32v234-palladium.dtb
dtb-$(CONFIG_S32V234_SIMULATOR) += s32v234-simulator.dtb
dtb-$(CONFIG_ARCH_FSL_LS2085A) += fsl-ls2085a-simu.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
