#
# Makefile for the QCOM spcific video device drivers
# based on V4L2.
#

obj-$(CONFIG_MSM_CAMSS_V4L2)    += camss-8x16/
obj-$(CONFIG_MSM_CCI)           += cci/
obj-$(CONFIG_MSM_VIDC_V4L2)     += vidc/
