#
# Makefile for the Qualcomm Technologies, Inc. FSM DP driver
#
obj-$(CONFIG_FSM_DP) += fsm_dp.o

fsm_dp-objs := fsm_dp_core.o fsm_dp_cdev.o fsm_dp_mhi.o fsm_dp_mem.o
fsm_dp-objs += fsm_dp_debugfs.o
