# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2019-2021 NXP
#

obj-$(CONFIG_CRYPTO_DEV_NXP_HSE) += hse.o

hse-y := hse-core.o hse-mu.o hse-uio.o
hse-y += hse-ahash.o hse-skcipher.o hse-aead.o hse-rng.o
