#
# Makefile for the Linux Kernel SOC fsl specific device drivers
#

obj-$(CONFIG_FSL_DPAA)                 += qbman/
obj-$(CONFIG_QUICC_ENGINE)		+= qe/
obj-$(CONFIG_CPM)			+= qe/
obj-$(CONFIG_FSL_GUTS)			+= guts.o
obj-$(CONFIG_S32_DEBUG_REGACCESS)	+= s32_regaccess.o
