obj-$(CONFIG_CRYPTO_DEV_FSL_CSE3) += cse3.o
cse3-y := cse3_core.o cse3_hw.o cse3_req.o
cse3-$(CONFIG_CRYPTO_DEV_FSL_CSE3_CRYPTO_API) += cse3_capi.o
cse3-$(CONFIG_CRYPTO_DEV_FSL_CSE3_HWRNG) += cse3_rng.o
