obj-$(CONFIG_FACTORY_UTIL) += fuse_check.o
obj-$(CONFIG_FACTORY_UTIL) += mcfg_check.o
obj-$(CONFIG_FACTORY_UTIL) += surface_util.o
obj-$(CONFIG_SURFACE_LIBRARY) += xbl_hlos_hob.o
obj-$(CONFIG_SURFACE_LIBRARY) += telemetry.o
