#
# Makefile for the Qualcomm Technologies, Inc. FSM TTI INTR driver
#
obj-$(CONFIG_FSM_TTI_INTR) += fsm_tti_intr.o

fsm_tti_intr-objs := fsm_tti_intr_debugfs.o fsm_tti_intr_cdev.o fsm_tti_intr_gpio.o
