# SPDX-License-Identifier: GPL-2.0

qnoc-sdm845-objs			:= sdm845.o
qnoc-smd-rpm-objs			:= smd-rpm.o

obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
obj-$(CONFIG_INTERCONNECT_QCOM_SMD_RPM) += qnoc-smd-rpm.o
