# SPDX-License-Identifier: GPL-2.0

qnoc-smd-rpm-objs			:= smd-rpm.o
qnoc-msm8916-objs			:= msm8916.o
qnoc-msm8996-objs			:= msm8996.o
qnoc-sdm845-objs			:= sdm845.o

obj-$(CONFIG_INTERCONNECT_QCOM_SMD_RPM) += qnoc-smd-rpm.o
obj-$(CONFIG_INTERCONNECT_QCOM_MSM8916) += qnoc-msm8916.o
obj-$(CONFIG_INTERCONNECT_QCOM_MSM8996) += qnoc-msm8996.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
