# for MSM 8960 sound card driver
obj-$(CONFIG_SND_SOC_MSM_QDSP6_INTF) += qdsp6/
snd-soc-qdsp6-objs :=  msm-pcm-q6.o msm-pcm-routing.o msm-dai-fe.o 
obj-$(CONFIG_SND_SOC_MSM_QDSP6_HDMI_AUDIO) += msm-dai-q6-hdmi.o
obj-$(CONFIG_SND_SOC_QDSP6) += snd-soc-qdsp6.o

snd-soc-msm8960-objs := apq8064.o 
obj-$(CONFIG_SND_SOC_MSM8960) += snd-soc-msm8960.o
