obj-$(CONFIG_QCOM_IOMMU) += qcom-iommu.o

qcom-iommu-y += msm_iommu.o
qcom-iommu-y += msm_iommu_domains.o
qcom-iommu-y += msm_iommu-v1.o
qcom-iommu-y += msm_iommu_dev-v1.o
qcom-iommu-y += msm_iommu_sec.o
qcom-iommu-y += msm_iommu_pagetable.o
#qcom-iommu-y += msm_iommu_mapping.o
