# Makefile for Qualcomm Venus driver

venus-objs += \
		core.o \
		helpers.o \
		vdec.o \
		vdec_ctrls.o \
		venc.o \
		venc_ctrls.o \
		hfi_venus.o \
		hfi_msgs.o \
		hfi_cmds.o \
		hfi.o \

obj-$(CONFIG_VIDEO_QCOM_VENUS) += venus.o
