ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sensor_module/cam_sensor
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils

obj-$(CONFIG_MSM_AIS_SENSOR_SERDES) += cam_sensor_serdes_dev.o
