name: snapdragon-kernel
summary: Snapdragon kernel for snappy
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core18

parts:
    kernel:
        after:
            - initrd
            - skales
            - firmware
            - firmware-ath10k
            - firmware-dragonboard410c
            - firmware-dragonboard820c
            - firmware-dragonboard845c
            - firmware-qcom-media
        plugin: kernel
        source: .
        source-type: git
        kconfigflavour: snapdragon
        kernel-with-firmware: false
        kernel-image-target: Image.gz
        kconfigs:
            - CONFIG_DEBUG_INFO=n
            - CONFIG_BLK_DEV_DM=y
            - CONFIG_DM_CRYPT=y
        override-build: |
            cp debian/scripts/retpoline-extract-one \
                ${SNAPCRAFT_PART_BUILD}/scripts/ubuntu-retpoline-extract-one
            snapcraftctl build
            cp ${SNAPCRAFT_PART_INSTALL}/dtbs/qcom/*.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
            ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
            snapcraftctl set-version $(git describe --tags | cut -c 19-42)
        stage:
            - System.map-*
            - config-*
            - dtbs
            - kernel.img
            - lib
            - modules
        prime:
            - -kernel.img

    initrd:
        plugin: nil
        source: initrd-overlay
        stage-packages:
            - on arm64:
                - cryptsetup-bin
                - dmsetup
                - e2fsprogs
                - rsync
                - libargon2-0
                - libcryptsetup12
                - libgcrypt20
                - libgpg-error0
                - libjson-c3
            - else:
                - cryptsetup-bin:arm64
                - dmsetup:arm64
                - e2fsprogs:arm64
                - rsync:arm64
                - libargon2-0:arm64
                - libcryptsetup12:arm64
                - libgcrypt20:arm64
                - libgpg-error0:arm64
                - libjson-c3:arm64
        override-build: |
            echo "Cleaning staged packages first"
            for d in lib/x86_64-linux-gnu \
                     usr/lib/x86_64-linux-gnu \
                     lib/systemd etc usr/share \
                     usr/lib/gcc \
                     var \
                     sbin/e2fsck \
                     sbin/dumpe2fs \
                     sbin/resize2fs
            do
                [ -e ${SNAPCRAFT_PART_INSTALL}/${d} ] && rm -rf ${SNAPCRAFT_PART_INSTALL}/${d}
            done
            find  ${SNAPCRAFT_PART_INSTALL}/lib/ \
               ! -name "libcryptsetup.so.*" \
               ! -name "libgcrypt.so.*" \
               ! -name "libgpg-error.so.*" \
               ! -name "libcrypto.so*" \
               ! -name "libssl.so*" \
               ! -name "libbsd.so*" \
               ! -name "libjson-c.so*" \
               ! -name "*.rules" \
               \( -type f -o -type l \) \
               -exec rm -v {} \;
            find  ${SNAPCRAFT_PART_INSTALL}/usr/lib \
               ! -name "libargon2.so*" \
               ! -name "libonig.so.*" \
               \( -type f -o -type l \) \
               -exec rm -v {} \;
            cp -r ${SNAPCRAFT_PART_INSTALL}/* ${SNAPCRAFT_PART_BUILD}/
            echo "Preparing overlay initrd"
            find . | cpio --create --quiet --format='newc' --owner=0:0 | lzma -7 > ${SNAPCRAFT_PART_INSTALL}/initrd-overlay.img
            wget https://people.canonical.com/~okubik/uc18_initrds/initrd-arm64.img -O ${SNAPCRAFT_PART_INSTALL}/initrd-clean.img
            cat ${SNAPCRAFT_PART_INSTALL}/initrd-clean.img \
                ${SNAPCRAFT_PART_INSTALL}/initrd-overlay.img \
                > ${SNAPCRAFT_PART_INSTALL}/initrd.img
        stage:
            - initrd.img

    bootimg-db845:
        plugin: nil
        after:
            - kernel
            - initrd
        override-build: |
            cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/sdm845-db845c.dtb > Image.gz+dtb845
            mkbootimg \
                --kernel Image.gz+dtb845 \
                --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
                --output ${SNAPCRAFT_PART_INSTALL}/boot.img \
                --pagesize 4096 \
                --base 0x80000000 \
                --kernel_offset 0x8000 \
                --ramdisk_offset 0x1000000 \
                --tags_offset 0x100 \
                --cmdline 'console=tty0 console=ttyMSM0,115200n8 root=/dev/disk/by-label/writable init=/lib/systemd/systemd ro rng_core.default_quality=700 fixrtc clk_ignore_unused pd_ignore_unused'
        prime:
            - boot.img

    bootimg:
        plugin: nil
        after:
            - kernel
            - skales
            - initrd
        override-build: |
            python3 ${SNAPCRAFT_STAGE}/skales/dtbTool -o dt.img -s 4096 ${SNAPCRAFT_STAGE}/dtbs/qcom/
            python3 ${SNAPCRAFT_STAGE}/skales/mkbootimg \
                --kernel=${SNAPCRAFT_STAGE}/kernel.img \
                --dt=dt.img \
                --pagesize 4096 \
                --base 0x80000000 \
                --ramdisk=${SNAPCRAFT_STAGE}/initrd.img \
                --cmdline="console=tty0 console=ttyMSM0,115200n8 root=/dev/disk/by-label/writable init=/lib/systemd/systemd ro rng_core.default_quality=700 fixrtc" \
                --output=${SNAPCRAFT_PART_INSTALL}/boot-db820c.img
            ln -f ${SNAPCRAFT_PART_INSTALL}/boot-db820c.img ${SNAPCRAFT_PART_INSTALL}/boot-db410c.img
        prime:
            - boot-db410c.img
            - boot-db820c.img

    firmware:
        plugin: nil
        stage-packages:
            - linux-firmware
            - linux-firmware-snapdragon:arm64
        override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/firmware/wlan ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx ${SNAPCRAFT_PART_INSTALL}/lib
            ln -s ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
        stage:
            - -firmware/amd
            - -firmware/amdgpu
            - -firmware/cavium
            - -firmware/dpaa2
            - -firmware/i915
            - -firmware/imx
            - -firmware/intel
            - -firmware/iwlwifi-*
            - -firmware/liquidio
            - -firmware/matrox
            - -firmware/mediatek
            - -firmware/mellanox
            - -firmware/mrvl
            - -firmware/netronome
            - -firmware/nvidia
            - -firmware/qed
            - -firmware/radeon
            - -firmware/rockchip
            - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
            - -firmware/ath3k-1.fw
            - -firmware/qcom/venus-5.2/venus.b00
            - -firmware/qcom/venus-5.2/venus.b01
            - -firmware/qcom/venus-5.2/venus.b02
            - -firmware/qcom/venus-5.2/venus.b03
            - -firmware/qcom/venus-5.2/venus.mdt
            - -firmware/ath10k/QCA4019/hw1.0/board-2.bin
            - -firmware/ath10k/QCA4019/hw1.0/firmware-5.bin
            - -firmware/ath10k/QCA6174/hw3.0/firmware-6.bin
            - -firmware/ath10k/QCA9887/hw1.0/firmware-5.bin
            - -firmware/ath10k/QCA9888/hw2.0/board-2.bin
            - -firmware/ath10k/QCA9888/hw2.0/firmware-5.bin
            - -firmware/ath10k/QCA988X/hw2.0/firmware-5.bin
            - -firmware/ath10k/QCA9984/hw1.0/board-2.bin
            - -firmware/ath10k/QCA9984/hw1.0/firmware-5.bin
            - -firmware/qca/rampatch_usb_00000302.bin
            - -firmware/qca/crnv32.bin
            - -firmware/wil6210.brd
            - -firmware/wil6210.fw
        organize:
            lib/firmware: firmware
        prime:
            - -usr
            - -lib

    firmware-ath10k:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-atheros_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard410c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard410c_1034.2.1-5_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware
        stage:
            - -boot

    firmware-dragonboard820c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard820c_01700.1-4_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard845c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard845c_20190529180356-v4+linaro5_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-qcom-media:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-media_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    skales:
        plugin: dump
        source: git://codeaurora.org/quic/kernel/skales
        organize:
            "*": skales/
        prime:
            - -*

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - wget
