name: snapdragon-kernel
version: nil
version-script: |
    git describe --tags | cut -c 19-42
summary: Snapdragon kernel for snappy
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core18

parts:
    kernel:
        plugin: kernel
        source: .
        source-type: git
        kconfigflavour: snapdragon
        kernel-with-firmware: false
        kernel-image-target: Image.gz
        kconfigs:
            - CONFIG_DEBUG_INFO=n
        override-build: |
            cp debian/scripts/retpoline-extract-one \
                ${SNAPCRAFT_PART_BUILD}/scripts/ubuntu-retpoline-extract-one
            snapcraftctl build
            cp ${SNAPCRAFT_PART_INSTALL}/dtbs/qcom/*.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
            ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
        stage:
            - System.map-*
            - config-*
            - dtbs
            - kernel.img
            - lib
            - modules
            - -modules/*/build
            - -modules/*/source
        prime:
            - -kernel.img

    firmware:
        plugin: nil
        stage-packages:
            - linux-firmware
            - wireless-regdb
        override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/firmware/wlan ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx ${SNAPCRAFT_PART_INSTALL}/lib
            ln -s ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
        stage:
            - -firmware/amd
            - -firmware/amdgpu
            - -firmware/cavium
            - -firmware/dpaa2
            - -firmware/i915
            - -firmware/imx
            - -firmware/intel
            - -firmware/iwlwifi-*
            - -firmware/liquidio
            - -firmware/matrox
            - -firmware/mediatek
            - -firmware/mellanox
            - -firmware/mrvl
            - -firmware/netronome
            - -firmware/nvidia
            - -firmware/qed
            - -firmware/radeon
            - -firmware/rockchip
            - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
            - -firmware/ath3k-1.fw
            - -firmware/qcom/venus-5.2/venus.b00
            - -firmware/qcom/venus-5.2/venus.b01
            - -firmware/qcom/venus-5.2/venus.b02
            - -firmware/qcom/venus-5.2/venus.b03
            - -firmware/qcom/venus-5.2/venus.mdt
            - -firmware/ath10k/QCA4019/hw1.0/board-2.bin
            - -firmware/ath10k/QCA4019/hw1.0/firmware-5.bin
            - -firmware/ath10k/QCA6174/hw3.0/firmware-6.bin
            - -firmware/ath10k/QCA9887/hw1.0/firmware-5.bin
            - -firmware/ath10k/QCA9888/hw2.0/board-2.bin
            - -firmware/ath10k/QCA9888/hw2.0/firmware-5.bin
            - -firmware/ath10k/QCA988X/hw2.0/firmware-5.bin
            - -firmware/ath10k/QCA9984/hw1.0/board-2.bin
            - -firmware/ath10k/QCA9984/hw1.0/firmware-5.bin
            - -firmware/qca/rampatch_usb_00000302.bin
            - -firmware/qca/crnv32.bin
            - -firmware/wil6210.brd
            - -firmware/wil6210.fw
        organize:
            lib/firmware: firmware
        prime:
            - -usr
            - -lib

    firmware-atheros:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-atheros_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard410c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard410c_1034.2.1-5_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware
        stage:
            - -boot

    firmware-dragonboard820c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard820c_01700.1-4_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard845c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard845c_20190529180356-v4+linaro5_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-qcom-media:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-media_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-qcom-soc:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-soc_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - wget
