obj-$(CONFIG_WCN36XX) := wcn36xx.o wcn36xx-platform.o
wcn36xx-y +=   main.o \
               dxe.o \
               txrx.o \
               smd.o \
               pmc.o \
               debug.o

wcn36xx-platform-y	+= wcn36xx-msm.o\
	wcnss_core.o
